# Generated by Django 4.1.7 on 2023-04-30 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_quantity_sale_no_of_items_remove_sale_product_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='store',
        ),
    ]
