# Generated by Django 4.1.7 on 2023-05-07 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_quantity_wholesale_no_of_items_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wholesale',
            old_name='unit_price',
            new_name='total_price',
        ),
    ]
