# Generated by Django 4.1.7 on 2023-05-07 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_rename_unit_price_wholesale_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='wholesale_items',
            name='product_total_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
