# Generated by Django 4.1.7 on 2023-05-07 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_wholesale_items_product_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='product_total_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
